### ISSUE TITLE
Large BQ files - potentially zipping before pushing to GitHub

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/datalab-pandas#14]
During creation of this [notebook](https://github.com/ebmdatalab/jupyter-notebooks/blob/master/nonCCG%20concessions/Addaction.ipynb) I came across an issue with the BQ producing a file too large to be uploaded to Git. Although i didn't really need to upload this file to Git this time, we will do in the future.

![image](https://user-images.githubusercontent.com/40460354/55085886-51912680-509f-11e9-8a7c-9060848dc249.png)

**Comment by sebbacon** [comment]
It turns out this is supported in newer versions of pandas, so I've upgraded the underlying libraries (you may need to upgrade datalab-pandas)

Documentation updated here: https://github.com/ebmdatalab/datalab-pandas/commit/c679a66d91cadcb1db15c82faab9e8d9504cc4d1
