### ISSUE TITLE
Incorrect multiplication x100 of deciles chart

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/datalab-pandas#8]
The deciles chart automatically multiplies the y-axis by 100.  I'm assuming this is due to the original code having this calculation in it in order to remove the need for percentage formatting on the y-axis.

Ideally a flag (e.g. `percentage=False`) could be part of the deciles chart code, to enable this to be switched on or off.

Error:

![image](https://user-images.githubusercontent.com/18683239/53800701-35351a80-3f35-11e9-9db7-365065dacc74.png)

Original code:

![image](https://user-images.githubusercontent.com/18683239/53800712-3c5c2880-3f35-11e9-8905-89f811fe3a31.png)

**Comment by sebbacon** [comment]
I think the person writing the code should be responsible for changing the value data to whatever scale they want - would you agree?  (Rather than a flag)

**Comment by richiecroker** [comment]
that's fine, as long as clear in instructions.  Are you going to remove the 100* from the code?

**Comment by alexwalkercebm** [comment]
The deployed version currently has the multiplier from line 106 removed, but also needs this multiplier removed:
https://github.com/ebmdatalab/datalab-pandas/blob/4e16fea683ef7ac6ecee07c40e96e873bc42e9bb/ebmdatalab/charts.py#L115
